apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tss-system

resources:
  - tss-server-configmap.yaml
  - tss-server-deployment.yaml
  #- tss-server-pvc.yaml
  - tss-server-service.yaml
  - .config/tss-ingress.yaml