apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayRouteConfig
metadata:
  name: business-loans-routes-config
spec:
  service: 
    name: business-loans-brownfield-proxy
  routes:
    - predicates:
        - Path=/list-business-loans
        - Method=GET
      ssoEnabled: true
    - predicates:
        - Path=/process-donation/*/adoption-request/**
        - Method=POST
      ssoEnabled: true
      filters:
      - CircuitBreaker="business-loansCircuitBreaker,forward:/alternate-donation-service"
---
apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGateway
metadata:
  name: business-loans-gateway
spec:
  count: 1
  api:
    serverUrl: http://business-loans.tanzu.dekt.io
    title: Business Loans 
    description: APIs to help with processing business loans
    version: 0.5.0
    cors:
      allowedOrigins:
      - http://api-portal.tanzu.dekt.io
---
apiVersion: v1
kind: Service
metadata:
  name: business-loans-brownfield-proxy
spec:
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayMapping
metadata:
  name: business-loans-routes-mapping
spec:
  gatewayRef:
    name: business-loans-gateway
  routeConfigRef:
    name: business-loans-routes-config