apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayRouteConfig
metadata:
  name: sentiment-routes-config
spec:
  service: 
    name: sentiment-brownfield-proxy
  routes:
    - predicates:
        - Path=/list-sentiment
        - Method=GET
      ssoEnabled: true
    - predicates:
        - Path=/process-donation/*/adoption-request/**
        - Method=POST
      ssoEnabled: true
      filters:
      - CircuitBreaker="sentimentCircuitBreaker,forward:/alternate-donation-service"
---
apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGateway
metadata:
  name: sentiment-gateway
spec:
  count: 1
  api:
    serverUrl: http://sentiment.tanzu.dekt.io
    title: User Sentiments
    description: APIs to help with user sentiments 
    version: 0.5.0
    cors:
      allowedOrigins:
      - http://api-portal.tanzu.dekt.io
---
apiVersion: v1
kind: Service
metadata:
  name: sentiment-brownfield-proxy
spec:
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayMapping
metadata:
  name: sentiment-routes-mapping
spec:
  gatewayRef:
    name: sentiment-gateway
  routeConfigRef:
    name: sentiment-routes-config