apiVersion: networking.k8s.io/v1beta1 
kind: Ingress 
metadata: 
  name: dekt4pets-ingress
  annotations: 
    kubernetes.io/ingress.class: nginx 
spec: 
  rules: 
    - host: dekt4pets.{HOST_NAME}
      http: 
        paths: 
          - backend: 
              serviceName: dekt4pets-gateway
              servicePort: 80