apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dekt4pets-ns

resources:
  - dekt4pets-backend-app.yaml
  - dekt4pets-backend-routes.yaml
  - dekt4pets-frontend-app.yaml
  - dekt4pets-frontend-routes.yaml
  - mapping.yaml
  - gateway.yaml
 
