apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayRouteConfig
metadata:
  name: datacheck-routes-config
spec:
  service: 
    name: datacheck-service
  routes:
    - predicates:
        - Path=/api/adoption-history/*
        - Method=GET
      filters:
        - RateLimit=3,60s
    - predicates:
        - Path=/api/criminal-record/*
        - Method=GET
      ssoEnabled: true
      tokenRelay: true
    - predicates:
        - Path=/api/house-visit-request/*/date/**
        - Method=POST,PUT,DELETE
      ssoEnabled: true
      tokenRelay: true