apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayRouteConfig
metadata:
  name: datacheck-routes-config
spec:
  service: 
    name: datacheck-brownfield-proxy
  routes:
    - uri: https://opentdb.com
      predicates:
        - Path=/api.php
        - Method=GET
        - Query=difficulty
      title: "Generate check-adoper question"
      description: "Generate a random true/false animal's related question for adopter knowledge check. Difficulty choices: easy, medium, hard "
    - predicates:
        - Path=/api/adoption-history/*
        - Method=GET
      filters:
        - RateLimit=3,60s
    - predicates:
        - Path=/api/criminal-record/*
        - Method=GET
      ssoEnabled: true
      tokenRelay: true
    - predicates:
        - Path=/api/house-visit-request/*/date/**
        - Method=POST,PUT,DELETE
      ssoEnabled: true
      tokenRelay: true
---
apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGateway
metadata:
  name: datacheck-gateway
spec:
  count: 1
  api:
    serverUrl: http://datacheck.{HOST_NAME}
    title: Background Check Services
    description: APIs to help with background checks on pet adopters
    version: 0.5.0
    cors:
      allowedOrigins:
      - http://api-portal.{HOST_NAME}
---
apiVersion: v1
kind: Service
metadata:
  name: datacheck-brownfield-proxy
spec:
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayMapping
metadata:
  name: datacheck-routes-mapping
spec:
  gatewayRef:
    name: datacheck-gateway
  routeConfigRef:
    name: datacheck-routes-config