apiVersion: kp.kpack.io/v1alpha1
kind: DependencyDescriptor
defaultClusterBuilder: base
defaultStack: base
stores:
- name: default
  sources:
  - image: registry.pivotal.io/tanzu-go-buildpack/go@sha256:64ba98089642bdb1ae22fde9b12fb905e0034a2e99c4564249bbc5190dcef8f9
  - image: registry.pivotal.io/tanzu-java-buildpack/java@sha256:2cad7d20a18d21bfd28630e67f7a758cf3d6e97f5b8e9a59292384f6d7d130d1
  - image: registry.pivotal.io/tanzu-nodejs-buildpack/nodejs@sha256:5050ac76d043395422e4ae3cab74d5bb31dc4e9f66414d0be3c4ebb7d1276312
  - image: registry.pivotal.io/tanzu-java-native-image-buildpack/java-native-image@sha256:12f8ff3e904d1698442c05a73a7318bfbbaf535e582704ff02f675d1fe4ebe7f
  - image: registry.pivotal.io/tanzu-dotnet-core-buildpack/dotnet-core@sha256:9ecfbe3c3565f6bc15d5aa116615cf33195a5d27133438d285f9d812f5c72664
  - image: registry.pivotal.io/tbs-dependencies/tanzu-buildpacks_php@sha256:fd5abb334f4adbcf46f42977992af145db04fb262d4c516ff4264f94e1fcd689
  - image: registry.pivotal.io/tbs-dependencies/tanzu-buildpacks_nginx@sha256:e67d5cd2e5240a9eb7a899b9b5d979ad85d0cf6c8182e15424516dac9f577371
  - image: registry.pivotal.io/tbs-dependencies/tanzu-buildpacks_httpd@sha256:34989fb8e264ccaea7916a9017b306d621b017920f71439fc515164ac0484cf5
  - image: registry.pivotal.io/tbs-dependencies/paketo-buildpacks_procfile@sha256:bf6a4265db23ae25b34d402cd24e04c36dccdf24d6a6b9297f1d154a9d0b8062
stacks:
- name: tiny
  buildImage:
    image: registry.pivotal.io/tanzu-tiny-bionic-stack/build@sha256:2775935b319ada89a0f48eee9a994205fafe7f48fe48e74ff026f10d229f89c1
  runImage:
    image: registry.pivotal.io/tanzu-tiny-bionic-stack/run@sha256:45f995c761637a9a28dc5b4e4d461369b69b0db71c2ea890f4be43327cd676ce
- name: base
  buildImage:
    image: registry.pivotal.io/tanzu-base-bionic-stack/build@sha256:00bea4d6ff08f84bea03a126375cf236cfec3de30735a59c1a540d0c1c9374fc
  runImage:
    image: registry.pivotal.io/tanzu-base-bionic-stack/run@sha256:d7ce225d0061cc80333a06577faeed266efe9e74c578470a948517b668b5630c
- name: full
  buildImage:
    image: registry.pivotal.io/tanzu-full-bionic-stack/build@sha256:0e3b7ccfe4511d4479daa91969116b9da3398c467ca9627fc3774ec42b077bbf
  runImage:
    image: registry.pivotal.io/tanzu-full-bionic-stack/run@sha256:166e40934c461ecf15c11ff9fb581323fe5e94abc02e6a044f09f60a61bbb85f
clusterBuilders:
- name: base
  stack: base
  store: default
  order:
  - group:
    - id: tanzu-buildpacks/dotnet-core
  - group:
    - id: tanzu-buildpacks/nodejs
  - group:
    - id: tanzu-buildpacks/go
  - group:
    - id: tanzu-buildpacks/php
  - group:
    - id: tanzu-buildpacks/nginx
  - group:
    - id: tanzu-buildpacks/httpd
  - group:
    - id: tanzu-buildpacks/java-native-image
  - group:
    - id: tanzu-buildpacks/java
  - group:
    - id: paketo-buildpacks/procfile
- name: full
  stack: full
  store: default
  order:
  - group:
    - id: tanzu-buildpacks/dotnet-core
  - group:
    - id: tanzu-buildpacks/nodejs
  - group:
    - id: tanzu-buildpacks/go
  - group:
    - id: tanzu-buildpacks/php
  - group:
    - id: tanzu-buildpacks/nginx
  - group:
    - id: tanzu-buildpacks/httpd
  - group:
    - id: tanzu-buildpacks/java-native-image
  - group:
    - id: tanzu-buildpacks/java
  - group:
    - id: paketo-buildpacks/procfile
- name: tiny
  stack: tiny
  store: default
  order:
  - group:
    - id: tanzu-buildpacks/go
  - group:
    - id: tanzu-buildpacks/java-native-image
  - group:
    - id: paketo-buildpacks/procfile
