apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayRouteConfig
metadata:
  name: dekt4pets-frontend-routes-config
spec:
  service: 
    name: dekt4pets-frontend-service
  routes:
    - predicates:
        - Path=/rescue/login
        - Method=GET
      filters:
        - RedirectTo=302, /rescue
      ssoEnabled: true
      order: 0
      tags:
        - adoptions
    - predicates:
        - Path=/rescue/**
        - Method=GET
      order: 1000
      tags:
        - pets