apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayRouteConfig
metadata:
  name: dekt4pets-backend-routes-config
spec:
  service: 
    name: dekt4pets-backend-service
  routes:
    - predicates:
        - Path=/api/animals
        - Method=GET
      filters:
        - RateLimit=2,15s
      tags:
        - Adoptions
    - predicates:
        - Path=/api/whoami
        - Method=GET
      tags:
        - Adopters
      ssoEnabled: true
      tokenRelay: true
    - predicates:
        - Path=/api/animals/*/adoption-requests/**
        - Method=POST,PUT,DELETE
      ssoEnabled: true
      tokenRelay: true
      tags:
        - Adoptions
      model:
        requestBody:
          description: Manage adoption requests
          content:
            'application/json':
              schema:
                type: object
                description: Adoption request schema
                properties:
                  adopterName:
                    type: string
                  email:
                    type: string
                    format: email
                  notes:
                    type: string
                required: [ "adopterName", "email" ]