apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGateway
metadata:
  name: dekt4pets-gateway
spec:
  api:
    serverUrl: http://dekt4pets.{HOST_NAME} #do not change animal-rescue due to a hard code bug in the app
    title: "Dekt4pets"
    description: "Micro Gateway to control internal APIs for building the dekt4pets online store"
    documentation: "https://vmware.wavefront.com/u/1RyhnsRys4?t=vmware"
    version: "1.0.0-K8s"
    cors:
      allowedOrigins:
      - "http://api-portal.tanzu.dekt.io"
  count: 2
  sso:
    secret: sso-secret
  observability:
    metrics:
      wavefront:
        enabled: true
    wavefront:
      secret: wavefront-secret
      source: dekt4pets-gateway
      application: dekt4pets
      service: dekt4pets-gateway