apiVersion: apps/v1
kind: Deployment
metadata:
  name: dekt4pets-frontend
spec:
  selector:
    matchLabels:
      app: dekt4pets-frontend
  template:
    metadata:
      labels:
        app: dekt4pets-frontend
    spec:
      containers:
        - name: dekt4pets-frontend
          image: springcloudservices/animal-rescue-frontend
          ports:
            - containerPort: 8080
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: dekt4pets-frontend
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: dekt4pets-frontend


