apiVersion: networking.k8s.io/v1beta1 
kind: Ingress 
metadata: 
  name: acc-ingress
  annotations: 
    kubernetes.io/ingress.class: nginx 
spec: 
  rules: 
    - host: acc.{HOST_NAME}
      http: 
        paths: 
          - backend: 
              serviceName: acc-server
              servicePort: 80