apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGateway
metadata:
  name: datacheck-gateway
spec:
  count: 1
  api:
    serverUrl: https://datacheck.dekt-apps-new.dekt.io
    title: Background Check Services
    description: APIs to help with background checks on pet adopters
    version: 0.5.0
