apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGateway
metadata:
  name: donations-gateway
spec:
  count: 1
  api:
    serverUrl: https://donations.{REPLACED_IN_RUNTIME}
    title: Donation Processing 
    description: APIs to help with processing donations 
    version: 0.5.0
