apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGateway
metadata:
  name: suppliers-gateway
spec:
  count: 1
  api:
    serverUrl: https://suppliers.{REPLACED_IN_RUNTIME}
    title: Suppliers Payments
    description: APIs to help with issuing payments to suppliers
    version: 0.5.0
