apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: sbo-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: sbo.apps.dekt.io
      http:
        paths:
          - path: "/"
            backend:
              serviceName: spring-boot-observer-server
              servicePort: 5112