apiVersion: networking.k8s.io/v1beta1 
kind: Ingress 
metadata: 
  name: api-hub-ingress
  annotations: 
    kubernetes.io/ingress.class: contour 
spec: 
  rules: 
    - host: api-hub.{HOST_NAME}
      http: 
        paths: 
          - backend: 
              serviceName: api-portal-server
              servicePort: 8080