apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGateway
metadata:
  name: datacheck-gateway
spec:
  count: 1
  api:
    serverUrl: https://datacheck.{HOST_NAME}
    title: Background Check Services
    description: APIs to help with background checks on pet adopters
    version: 0.5.0
    cors:
      allowedOrigins:
        - api-portal.{HOST_NAME}
